id: 5e6806e4254f42f9a40738c26bf6fe92
initial_creation_type: ocr
source_metadata:
  volumes:
    36de96bf26344a2c9a558684a82660b5:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ''
      total_pages: 1539
      volume_number: 1
